### ISSUE TITLE
 Continuous appearance and disappearance of terminal windows

### ISSUE THREAD

**Issue by AytoMaximo** [vanBassum/Wakatime.Unity#15] opened 2023-04-13 07:16 UTC
I use Windows 11 and Unity 2021.3.20f1. When the plugin attempts to send something to the server, it calls a CLI command program. I notice a lot of terminal windows appearing and disappearing quickly, which is really disrupting my work. How can I fix this?

**Comment by vanBassum** [comment] 2023-04-16 13:30
This issue has occurred before and fixed before, do you have the latest main?

**Comment by AytoMaximo** [comment] 2023-04-17 09:50
> This issue has occurred before and fixed before, do you have the latest main?

Yes, I'm sure I'm using the latest version. I've never used this plugin before, so I discovered it on the same day that I wrote this issue. First, I installed it by adding the Git URL to the package manager, so it should have automatically downloaded the latest version. However, I then encountered the problem I described. I attempted to download the repository manually and put it in the assets folder so that I could edit the code (which is not possible if the plugin exists in packages), but I was unable to fix it properly.

**Comment by vanBassum** [comment] 2023-04-17 10:31
I'll see if I can fix the issue once I find the time to get around to this. In the meantime, here is all the information that was collected so far for this issue.

I was already afraid this would happen before I created the Wakatime CLI implementation.
- https://github.com/vanBassum/Wakatime.Unity/issues/7

For more information and things we have tried before, see:
- https://github.com/vanBassum/Wakatime.Unity/issues/8
- https://github.com/vanBassum/Wakatime.Unity/pull/9

If you want to try fixing this yourself, the following file is probably where you can find the issue:
- https://github.com/vanBassum/Wakatime.Unity/blob/main/Editor/Utils/ProcessRunner.cs

This code is based on the example given by Wakatime: 
- https://github.com/wakatime/nuget-wakatime-shared-extension-utils/blob/master/src/WakaTime.Shared.ExtensionUtils/RunProcess.cs

Of course, If you have any questions, I'm glad to help you.

**Comment by vanBassum** [comment] 2023-05-08 17:33
I can't reproduce this issue on my windows 10 system. I should try this again on a windows 11 system.

**Comment by vanBassum** [comment] 2023-12-14 12:07
Merged the fix from @Kryeker to the main

**Closed by vanBassum** 2023-12-14 12:07 UTC
Labels: bug
